### ISSUE TITLE
When Using the Template with an existing VPC and Existing IGW Template is invalid

### ISSUE THREAD

**Issue by kstrini** [sradnidge/cf-ha-aws#1]
Using the template to co deploy pcf within an existing VPC with and existing IGW throws the following error

Template validation error: Template format error: Unresolved resource dependencies [InternetGateway] in the Resources block of the template

**Comment by sradnidge** [comment]
I'm going to remove the ability to specify existing VPC / IGW for now... it has some other implications that I didn't fully think through initially! Also, I have never actually had a need to use it in reality :)
